Repository LCOGT/datalab-ui, pull requests merged in 2024-11, with the labels that each got.

#110 Support for Open in Datalab, Project View query params
  src/router/index.js
  src/utils/common.js
  src/views/ProjectView.vue
Labels: enhancement

#109 Analysis data improvements
  src/components/Global/ImageGrid.vue
  src/components/Project/ImageAnalysis/ImageAnalyzer.vue
  src/components/Project/ImageList.vue
  src/stores/alerts.js
  src/utils/common.js
Labels: enhancement

#111 Feature/rgb image scaling
  package-lock.json
  package.json
  public/drawImageWorker.js
  src/components/DataSession/OperationWizard.vue
  src/components/Global/CompositeImage.vue
  src/components/Global/ImageScaler.vue
  src/components/Global/ImageScalingGroup.vue
  src/components/Global/RawScaledImage.vue
  src/stores/scaling.js
  src/stores/thumbnails.js
  src/utils/common.js
  vue.config.js
Labels: enhancement

#115 removed clearing of imagesByProposal
  src/views/ProjectView.vue
Labels: code cleanup

#119 fix hydration error for vue config
  vue.config.js
Labels: bug
